export const INSTAGRAM = 'https://www.instagram.com/geekrodion/'
export const LINKEDIN = 'https://www.linkedin.com/in/geekrodion/'
export const YOUTUBE = 'https://www.youtube.com/channel/UC15iv69GgcJWa8GoohNQzpw'
export const MEDIUM = 'https://medium.com/@geekrodion'
export const GITHUB = 'https://github.com/RodionChachura'
export const TWITTER = 'https://twitter.com/geekrodion'